# Module 2: Data Analytics with Python - Statistics

## Lab 1: Basic statistics & Linear Algebra

<br><br><br><br><br><br><br><br><br>
## About Libraries for Statistics
***

### NUMPY

NumPy is short for "Numerical Python". It is used to work with arrays. In Python we have lists that serve the purpose of arrays, but they are slow to process. NumPy aims to provide an array object that is twice faster then traditional Python lists.

### SCIPY

SciPy is a free and open-source Python library used for scientific computing and technical computing. 
SciPy contains modules for optimization, linear algebra, integration, interpolation, special functions, 
FFT, signal and image processing, ODE solvers and other tasks common in science and engineering.

In [ ]:
import sys

# run this cell to install numpy
!{sys.executable} -m pip install numpy

# run this cell to install scipy
!{sys.executable} -m pip install scipy

<br><br><br><br><br><br>
# Objevtive
***
- **Measures of Central Tendency**
     - Mean
     - Median
     - Mode

- **Measures Of Spread**

     - Range
     - Quartiles and Interquartile range
     - Percentile
     - Variance
     - Standard deviation


- **Correlation v/s Causation**
- **Kurtosis**
- **Skewness**
- **Eigen Vectors**

     

In [ ]:
import numpy as np

# Creating a Basic Array in Numpy
X=np.array([1,2,3,5,5])

<br><br><br><br><br><br>
## Measures of Central Tendency 
***

The measure of central tendency is the commonly used method to identify the centre of the data set.
Used to describe a data set by identifying the central position within that data set.

Mean, Median and Mode

### MEAN
***
The most popular measure of central tendency. ​ It is also referred to as the average value in the data set. ​Defined as the sum of all values in a data set, divided by the total number of values in a data set.​ 

$ \bar X= \frac{\sum X}{n}$

In [ ]:
# Mean using Numpy
print("Data",X)
print("Mean:",np.mean(X))

Data [1 2 3 5 5]
Mean: 3.2


<br><br><br>
### MEDIAN
***
Median is the middle value of an ordered data set. If there are a total of n values. Then median is -

1. $ \frac {(n+1)}{2} $th term if n is odd.


2. Average of ($\frac{n}{2}$) and ($\frac{n}{2}+1$)th terms, if n is even.

In [ ]:
# Finding Median of X
print("Data",X)
print("Median",np.median(X))
print("Tipe",type(np.median(X)))

Data [1 2 3 5 5]
Median 3.0
Tipe <class 'numpy.float64'>


<br><br><br>
### MODE
***

1. Most frequently occurring value in the data set, i.e. value of the random sample that occurs with the greatest frequency.
2. It is applicable to all levels of data measurement, i.e., nominal, ordinal, interval and ratio scales.

In [ ]:
# Finding Mode using numpy
print("Data",X)
vals,counts = np.unique(X, return_counts=True)
index = np.argmax(counts)
print("Mode:",vals[index])


# Finding Mode using Scipy

from scipy import stats
m = stats.mode(X)
print("Mode:",stats.mode(X))
print("Mode:",m[0][0])

Data [1 2 3 5 5]
Mode: 5
Mode: ModeResult(mode=array([5]), count=array([2]))
Mode: 5


<br><br><br><br><br><br>
## Measures of Spread
***

A measure of how the data is dispersed or spread around the mean, i.e. the average.  It is used in quantitative data, as the variables can be arranged in a logical order, with a low and high value.

Spread can be measured in-
1.	Range 
2.	Quartiles and Interquartile range 
3.	Percentile
4.	Variance 
5.	Standard deviation 


### RANGE
***
1. It is the simplest measure of variability. 
2. The distance between the smallest value and the largest value in a dataset. 

$ Range= \max(X)-\min(X)$

In [ ]:
# Calculating the Range
print("Data ",X)
print("Range ",X.max()-X.min())

Data  [1 2 3 5 5]
Range  4


<br><br><br><br><br><br>
### QUARTILES AND IQR(Interquartile Range)
***

1. Q1 is the "middle" value in the first half of the rank-ordered data set.
2. Q2 is the median value in the set.
3. Q3 is the "middle" value in the second half of the rank-ordered data set.
4. The interquartile range is calculated as: Upper Quartile – Lower Quartile.

In [ ]:
# Defining Data
data1=np.array([1, 3, 4, 5, 5, 6, 7, 11])
print("Data",data1)

# First quartile (Q1)
Q1 = np.quantile(data1, .25, interpolation = 'midpoint')
print("\nQuartile 1:",Q1)
 
# Second quartile (Q2)
Q2 = np.quantile(data1, .50, interpolation = 'midpoint')
print("Quartile 2:",Q2)

# Third quartile (Q3)
Q3 = np.quantile(data1, .75, interpolation = 'midpoint')
print("Quartile 3:",Q3)

# Interquaritle range (IQR)
IQR = Q3 - Q1
print("\nInterquartile Range",IQR)

Data [ 1  3  4  5  5  6  7 11]

Quartile 1: 3.5
Quartile 2: 5.0
Quartile 3: 6.5

Interquartile Range 3.0


<br><br><br><br><br><br>
### PERCENTILES
***

The percentile usually indicates that a certain percentage falls below that percentile. For example, if you score in the 25th percentile, then 25% of test takers are below your score. The “25” is called the percentile rank. 

In [ ]:
print("Data",data1)
percentile_20 = np.percentile(data1,20)
print("20th Percentile:",round(percentile_20,2))

Data [ 1  3  4  5  5  6  7 11]
20th Percentile: 3.4


<br><br><br>
### VARIANCE AND STANDARD DEVIATION
***
Variance is a measure of how the spread-out a data set is. The formula for variance is-

$\sigma^2 = \frac{\sum (X_{i}-\bar X)^2}{n-1}$

Standard Deviation is the square root of variance. It is denoted by greek letter sigma $\sigma$.

In [ ]:
print("Data",data1)

'''
    "Delta Degrees of Freedom": the divisor used in the calculation is
    ``N - ddof``, where ``N`` represents the number of elements. By
    default `ddof` is zero.
'''
print("Varaince:",np.var(data1,ddof=1))
print("Varaince:",np.var(data1))
print("Standard Deviation:",np.std(data1,ddof=1))

Data [ 1  3  4  5  5  6  7 11]
Varaince: 8.785714285714286
Varaince: 7.6875
Standard Deviation: 2.9640705601780613


<br><br><br><br><br><br>
## COVARIANCE AND CORRELATION
***

### COVARIANCE
1. Covariance is a statistical technique used for determining the relationship between the movement of two random variables. In short, how much two random variables change together.  

2. Provides a measure of the strength of the correlation between two or more sets of random variates.

3. Example: Let E(x) be the expected value of a given variable x, and E(y) be the expected value of variable y, then the covariance between x and y is given by:

$cov(x, y) = E[xy] − E[x] E[y]$

- If COV(x, y) = 0 then variables are uncorrelated
- If COV(x, y) > 0 then variables positively correlated
- If COV(x, y) > < 0 then variables negatively correlated

In [ ]:
x = np.array([1,2,3,4,5,6,7,8,9])
print(x)
y = np.array([9,8,7,6,5,4,3,2,1])
z = np.array([19,15,13,10,5,4,3,2,1])
print(y)

print("\nCovariance ",np.cov(x,y)[0,1])

[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]

Covariance  -7.5


<br><br><br><br><br><br>
### CORRELATION
***

1. It is the measure of the strength of the relation between two variables. How strongly two variables are connected is defined as the correlation. 

2. It depends upon two variables, change in one variable effect a change in second variable.

3. Its value lies in the range of -1 and +1. r is called the Pearson's correlation coefficient.

4. Is related to covariance by the given formula: 

$r= cov(x,y)/\sigma_x \sigma_y$

- A correlation coefficient greater than zero indicates a positive relationship while a value less than zero signifies a negative relationship.
- A value of zero indicates no relationship between the two variables being compared.

In [ ]:
# Return a correlation coefficient matrix
print(np.corrcoef(z,y))

[[1.       0.967769]
 [0.967769 1.      ]]


### Thank You !!!